#ifndef BOOKSHOP_VERSION_H_
#define BOOKSHOP_VERSION_H_

#define BOOKSHOP_VERSION "0.1.0"

#define BOOKSHOP_MAJOR_VERSION 0
#define BOOKSHOP_MINOR_VERSION 1
#define BOOKSHOP_PATCH_VERSION 0

#endif  // BOOKSHOP_VERSION_H_

